### ISSUE TITLE
Custom button not working

### ISSUE THREAD

**Issue by pnome** [calimarkus/JDStatusBarNotification#128]
I love this project. It's so easy to use and does just what I need. Thank you!

The only issue I'm having is that if I put a custom button in the banner (as per the example code), I'm unable to click the button.

I can swipe the banner away, just as in the example app, so it reacts to touches, but if I press the button the text doesn't get darker and whatever code I put in the closure isn't executed.

Could this be related to the fact that my code doesn't use scenes? Do you have any suggestions as to how I might get it working?

This is my code:
`    class func showTestBanner() {
        // present a custom view
        let button = UIButton(type: .system, primaryAction: UIAction { _ in
            print("BUTTON WAS TAPPED")
          NotificationPresenter.shared().dismiss()
        })
        button.setTitle("Dismiss!", for: .normal)
        NotificationPresenter.shared().present(customView: button, style: nil)
    }`

Thanks,
Joe

**Comment by calimarkus** [comment]
Checkout the docs here:

http://calimarkus.github.io/JDStatusBarNotification/documentation/jdstatusbarnotification/notificationpresenter/present(customview:style:completion:)

You need to set `style.canTapToHold = false` in order to handle touches yourself.

I should update the example in the readme also.

**Comment by calimarkus** [comment]
You can also checkout the code in the example project.

I updated the readme too.
